### PR TITLE
Jtorre39/wave

### PR DESCRIPTION
**Pull request by im-deepfriedwater**
This PR contains
- implementation of a wave manager: exists server-side and keeps track of how / when to spawn zombies, if a wave has ended (if players kill all zombies or if time has run out) and points
- implementation of a corresponding wave ui manager: exists both client and server-side. primarily on server it commands the client's copy to begin timers to update UI (e.g.: wave timer)  and periodically will sync up the timers to make sure they're not too far off of the server's.
- new UI includes a wave timer and a score count
- modifications to damagable enemy so when they die they count as points for the player
- a (horribly) coded implementation of a kill all enemies for when players survive the wave timer
- ~~does not contain a death or game over screen~~ it has now been updated to contain an game over overlay

### CODE REVIEW

**Review by CapnSquirrel — COMMENTED** [review]
We tested this PR between two clients.
- When both players died, the wave timer was stuck between 0:58 and bouncing back to 1:00; we never received the death. Is this intended behaviour?

**Comment by im-deepfriedwater** [comment]
this is probably an effect of not having the game over screen implemented and then the timer stops server side only but the server is still syncing the clients timer which is attempting to count down. having a game over screen fade-in to the users should mitigate this, but not sure how long that will take me, ill have to try it out

**Comment by im-deepfriedwater** [comment]
by receive the death do you mean the players didn't do a death animation? or a game over screen?

**Comment by im-deepfriedwater** [comment]
ok, addressed previous concerns and have the timer stopped properly,  PR is ready for review again, additionally a death text shows up when all players have died

**Review by CapnSquirrel — APPROVED** [review]
looks good to me...

**Pull request merged**
